import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ContractProvider } from "@/context/ContractContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
       <ContractProvider>
       <Header/>
        {children}
       <Footer /> 
        </ContractProvider> 
        </body>
    </html>
  );
}
